## Guidelines for the environmnet

# Creating environment
# conda env create -f environment_neurots.yml

# Activating the environment
# conda activate neurots-explore

# To make a NEUROTS-EXPLORE kernel:
# python -m ipykernel install --user --name neurots-explore --display-name "NEUROTS-EXPLORE"

# To update the pyphi-explore conda environment:
# conda env update -f environment_neurots.yml

# To remove and reinstall the neurots-explore environment (if installation problems):
# conda deactivate
# conda env remove -n neurots-explore

# Recreating the environment
# conda env create -f environment_neurots.yml


name: neurots-explore
channels:
  - conda-forge
dependencies:
  - python=3.9
  - jupyter
  - ipython
  - ipykernel
  - jupyterlab
  - psutil
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - statsmodels
  - imageio
  - scikit-learn
  - scikit-image
  - nilearn
  - git
  - pip
  - pip:
    # NeuroTS https://neurots.readthedocs.io/en/stable
    - neurots
    # NeuroM https://github.com/BlueBrain/NeuroM
    - neurom[plotly]
    # Napari https://github.com/napari/napari
    - napari[all]
    # Brainlit https://github.com/neurodata/brainlit
    - brainlit
